### ISSUE TITLE
Does not look good with the Atom Material UI

### ISSUE THREAD

**Issue by makerimages** [jerone/atom-new-tab#3]
This does not play well with the [Atom material UI](https://atom.io/themes/atom-material-ui). Everything is fine, but on hover, the + shifts to the right, out of the tab.

**Comment by jerone** [comment]
@makerimages Can you confirm if the following code fixes the issues:

``` less
.theme-atom-material-ui {
    .tab-bar {
        .tab.new-tab {
            text-align: center;
            .title {
                margin-top: 1px;
            }
        }
        .tab.new-tab.new-tab-sticky {
            width: -webkit-fit-content;
        }
    }
}
```
